alias: PV clipping - make room in battery at sunrise
description: >-
  Make room in battery at sunrise if PV clipping is forecast in the next 24 hours
triggers:
  - entity_id:
      - input_number.pv_clipped_in_next_24_hours
    trigger: state
conditions:
  - condition: numeric_state
    entity_id: predbat.rates
    above: 0
  - condition: template
    value_template: |
      {{ states('input_number.pv_clipped_in_next_24_hours') | float > 0 }}
actions:
  - metadata: {}
    data:
      option: >
        {# Round down the time to nearest half-hour #}   
        {% set t = utcnow().strftime("%s") | int %}   
        {{ (t - (t % 1800) + 16200) | timestamp_custom("%H:%M:%S") }}
    target:
      entity_id: select.predbat_manual_export
    action: select.select_option
  - metadata: {}
    data:
      option: >
        {# Round down the time to nearest half-hour #}   
        {% set t = utcnow().strftime("%s") | int %}   
        {{ (t - (t % 1800) + 14400) | timestamp_custom("%H:%M:%S") }}
    target:
      entity_id: select.predbat_manual_export
    action: select.select_option
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output rate. #}    
          {% set battery_max_output = namespace(value = 1.8) %}    
          {{ states('input_number.pv_clipped_in_next_24_hours') | float > battery_max_output.value }}
    then:
      - metadata: {}
        data:
          option: >
            {# Round up the time to nearest half-hour #}   
            {% set t = utcnow().strftime("%s") | int %}   
            {{ (t - (t % 1800) + 12600) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_export
        action: select.select_option
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output rate. #}    
          {% set battery_max_output = namespace(value = 1.8) %}    
          {{ states('input_number.pv_clipped_in_next_24_hours') | float > battery_max_output.value }}
    then:
      - metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    
            {{ (t - (t % 1800) + 10800) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_export
        action: select.select_option
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output rate. #}    
          {% set battery_max_output = namespace(value = 1.8) %}    
          {{ states('input_number.pv_clipped_in_next_24_hours') | float > (battery_max_output.value * 2) }}
    then:
      - metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    
            {{ (t - (t % 1800) + 9000) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_export
        action: select.select_option
  - if:
      - condition: template
        value_template: >-
          {#  Default is 1.8 kWh in 30 minutes. Change to your battery output rate. #}    
          {% set battery_max_output = namespace(value = 1.8) %}    
          {{ states('input_number.pv_clipped_in_next_24_hours') | float > (battery_max_output.value * 2) }}
    then:
      - metadata: {}
        data:
          option: >
            {% set t = utcnow().strftime("%s") | int %}    
            {{ (t - (t % 1800) + 7200) | timestamp_custom("%H:%M:%S") }}
        target:
          entity_id: select.predbat_manual_export
        action: select.select_option
mode: single
